### DISCUSSION TITLE
Error integrating sqlite-web

### DISCUSSION THREAD

**Discussion by opeolluwa** [xmtp/sqlite-web-rs#18] [Q&A]
Hello there, thank you for the awesome work on this crate, 
I was able to build the source successfully, but can't seem to use it an an application targeting wasm32-unknown-unknown environment. The build command `cargo build --lib  --target "wasm32-unknown-unknown"`, exits with this error \"

```sh
 /Users/USER/.cargo/git/checkouts/sqlite-web-rs-92f6701c073fab06/0aa5305/src/sqlite_fixes.rs:9:18
  |
9 |         AstPass, InsertOrIgnore, IntoUpdateTarget, NoFromClause, QueryFragment, Replace,
  |                  ^^^^^^^^^^^^^^ no `InsertOrIgnore` in `query_builder`          ^^^^^^^ no `Replace` in `query_builder`

error[E0432]: unresolved imports `diesel::query_builder::All`, `diesel::query_builder::Distinct`, `diesel::query_builder::Except`, `diesel::query_builder::Intersect`, `diesel::query_builder::ParenthesisWrapper`, `diesel::query_builder::SupportsCombinationClause`, `diesel::query_builder::Union`
   --> /Users/USER/.cargo/git/checkouts/sqlite-web-rs-92f6701c073fab06/0aa5305/src/sqlite_fixes.rs:165:9
    |
165 |         All, AstPass, Distinct, Except, Intersect, ParenthesisWrapper, QueryFragment,
    |         ^^^           ^^^^^^^^  ^^^^^^  ^^^^^^^^^  ^^^^^^^^^^^^^^^^^^ no `ParenthesisWrapper` in `query_builder`
    |         |             |         |       |
    |         |             |         |       no `Intersect` in `query_builder`
    |         |             |         no `Except` in `query_builder`
    |         |             no `Distinct` in `query_builder`
    |         no `All` in `query_builder`
166 |         SupportsCombinationClause, Union,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^ no `Union` in `query_builder`
    |         |
    |         no `SupportsCombinationClause` in `query_builder`
    |
    = help: consider importing this type alias instead:
            diesel::helper_types::Distinct
    = help: consider importing this type alias instead:
            diesel::helper_types::Except
    = help: consider importing this type alias instead:
            diesel::helper_types::Intersect
    = help: consider importing one of these items instead:
            std::collections::btree_set::Union
            std::collections::hash_set::Union
            diesel::helper_types::Union

error[E0407]: method `set_prepared_statement_cache_size` is not a member of trait `Connection`
   --> /Users/USER/.cargo/git/checkouts/sqlite-web-rs-92f6701c073fab06/0aa5305/src/connection/mod.rs:108:5
    |
108 | /     fn set_prepared_statement_cache_size(&mut self, size: diesel::connection::CacheSize) {
109 | |         self.statement_cache.set_cache_size(size)
110 | |     }
    | |_____^ not a member of trait `Connection`

error[E0412]: cannot find type `CacheSize` in module `diesel::connection`
   --> /Users/USER/.cargo/git/checkouts/sqlite-web-rs-92f6701c073fab06/0aa5305/src/connection/mod.rs:108:79
    |
108 |     fn set_prepared_statement_cache_size(&mut self, size: diesel::connection::CacheSize) {
    |                                                                               ^^^^^^^^^ not found in `diesel::connection`

Some errors have detailed explanations: E0407, E0412, E0432.
For more information about an error, try `rustc --explain E0407`.
error: could not compile `sqlite-web` (lib) due to 4 previous errors
```

**Comment by insipx** [comment]
Hello! Thanks for your interest in the project. It would help to post your `Cargo.toml` to help debug this.

Unfortunately, the [diesel-rs/diesel](https://github.com/diesel-rs/diesel) has not made a release including my changes to their imports yet, so this means you will need to depend on `sqlite-web-rs` and `diesel` as git dependencies. 

You can do this as a patch dependency, example here: https://github.com/xmtp/sqlite-web-rs/blob/0aa53058cbf3a1044e79cb6dd68a91c857308059/examples/web-sqlite/Cargo.toml#L41

**Comment by opeolluwa** [comment]
I've yanked the features

If I can ask, what's the best way to integrate this? 

Add diesel and this create to my project or just this crate?

**Reply by insipx** [reply]
You need diesel and the `sqlite-web-rs` crate

```toml
[package]
name = "example-sqlite-web"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
sqlite-web = { git = "https://github.com/xmtp/sqlite-web-rs", branch = "main" }
diesel = "2.2"

# patch needed until diesel makes a release that includes
# the latest changes
[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs/diesel", branch = "master" }
diesel_derives = { git = "https://github.com/diesel-rs/diesel", branch = "master" }
diesel_migrations = { git = "https://github.com/diesel-rs/diesel", branch = "master" }


[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
# Required for sqlite-web
split-linked-modules = true
```

This toml file is the bare minimum needed to use the sqlite-web crate. I created an #21 to re-export diesel for ease-of-use in the future

**Reply by opeolluwa** [reply]
Thank you so much, I'll try this out

**Reply by opeolluwa** [reply]
```toml 
[package]
name = "sqlite_wasm_bindgen"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
console_error_panic_hook = { version = "0.1.6" }
serde = "1"
serde-wasm-bindgen = "0.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-wasm = "0.2"
wasm-bindgen = "=0.2.99"
wasm-bindgen-futures = "0.4"
sqlite-web = { git = "https://github.com/xmtp/sqlite-web-rs", branch = "main" }
diesel = "2.2"

[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs/diesel", branch = "master" }
diesel_derives = { git = "https://github.com/diesel-rs/diesel", branch = "master" }
diesel_migrations = { git = "https://github.com/diesel-rs/diesel", branch = "master" }


[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
split-linked-modules = true
```

my toml, still the same error

**Reply by insipx** [reply]
I'm able to successfully compile with that `Cargo.toml`

what happens if you run `cargo update` to ensure the diesel patch is working? If `cargo update` does not let you compile the package with `cargo build --target wasm32-unknown-unknown`, I would request that you post the output of that command here so I can help debug it

![Screenshot 2024-12-27 at 17 24 59](https://github.com/user-attachments/assets/f178b713-6755-460c-831f-07f084e02e71)

**Comment by insipx** [comment]


**Reply by opeolluwa** [reply]
whoa!

**Reply by opeolluwa** [reply]
Let me just copy it over

**Reply by opeolluwa** [reply]
<img width="1512" alt="Screenshot 2024-12-28 at 20 40 26" src="https://github.com/user-attachments/assets/eb54e546-aa3f-48ec-846b-c60286565289" />
<img width="1512" alt="Screenshot 2024-12-28 at 20 40 39" src="https://github.com/user-attachments/assets/dc30cfa9-59dc-4f77-8812-7b6a7a905d4c" />



```toml 
[package]
name = "sqlite_wasm_bindgen"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
sqlite-web = { git = "https://github.com/xmtp/sqlite-web-rs", branch = "main" }
diesel = "2.2"

# patch needed until diesel makes a release that includes
# the latest changes
[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs/diesel", branch = "master" }
diesel_derives = { git = "https://github.com/diesel-rs/diesel", branch = "master" }
diesel_migrations = { git = "https://github.com/diesel-rs/diesel", branch = "master" }


[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
# Required for sqlite-web
split-linked-modules = true
```

@insipx It's still the same thing, is there anything I'm doing wrong
